# Generated by Django 1.11.20 on 2019-03-21 15:25


import json

from django.db import migrations


def move_overrides_to_edx_when(apps, schema_editor):
    from xmodule.fields import Date
    from edx_when import api
    date_field = Date()
    StudentFieldOverride = apps.get_model('courseware', 'StudentFieldOverride')
    for override in StudentFieldOverride.objects.filter(field='due'):
        try:
            abs_date = date_field.from_json(json.loads(override.value))
            api.set_date_for_block(
                override.course_id,
                override.location,
                'due',
                abs_date,
                user=override.student)
        except Exception:  # pylint: disable=broad-except
            # The following line is commented since these logs only add noise to output console
            # Thi migration only works with IDDE
            # log.exception("migrating %d %r: %r", override.id, override.location, override.value)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0007_remove_done_index'),
    ]

    operations = [
        migrations.RunPython(move_overrides_to_edx_when)
    ]
